"""
Representa un hecho del sistema
"""
type Hecho {
  id: ID
  titulo: String
  descripcion: String
  categoria: String
  latitud: String
  longitud: String
  fechaAcontecimiento: String
  fechaCarga: String
  etiqueta: String

  archivosMultimedia: [String]

  nombre_contribuyente: String
  apellido_contribuyente: String

  sugerencia_cambio: String
}

"""
Filtros disponibles para buscar hechos
"""
input HechoFiltroInput {
  sur: Float
  oeste: Float
  norte: Float
  este: Float
  titulo: String
  descripcion: String
  categoria: String
  estadoDeseado: String
  coleccionId: String
  modo: String
  contieneMultimedia: Boolean
  desdeAcontecimiento: String
  hastaAcontecimiento: String
  desdeCarga: String
  hastaCarga: String
}

type Query {
  obtenerHechosFiltrados(
    filtro: HechoFiltroInput
  ): [Hecho]
}