
x-db-env: &db_env
  SPRING_PROFILES_ACTIVE: docker
  DB_HOST: ${DB_HOST}
  DB_PORT: ${DB_PORT}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}

services:

  agregador:
    build:
      context: .
      dockerfile: agregador/Dockerfile
    container_name: metamapa-agregador
    ports:
      - "8200:8200"
    environment:
      <<: *db_env
      DB_NAME: metamapa_central
    networks: [metamapa-net]
    restart: unless-stopped

  gestor:
    build:
      context: .
      dockerfile: gestor-datos/Dockerfile
    container_name: metamapa-gestor
    ports:
      - "8500:8500"
    environment:
      <<: *db_env
      DB_NAME: metamapa_central
    networks: [metamapa-net]
    restart: unless-stopped

  estadisticas:
    build:
      context: .
      dockerfile: estadisticas/Dockerfile
    container_name: metamapa-estadisticas
    ports:
      - "8600:8600"
    environment:
      <<: *db_env
      DB_NAME: metamapa_central
    networks: [metamapa-net]
    restart: unless-stopped

  demo:
    build:
      context: .
      dockerfile: loader-demo/Dockerfile
    container_name: metamapa-demo
    ports:
      - "8700:8700"
    environment:
      <<: *db_env
      DB_NAME: loader_demo
    networks: [ metamapa-net ]
    restart: unless-stopped

  dinamico:
    build:
      context: .
      dockerfile: loader-dinamico/Dockerfile
    container_name: metamapa-dinamico
    ports:
      - "8102:8102"
    environment:
      <<: *db_env
      DB_NAME: loader_dinamico
    networks: [ metamapa-net ]
    restart: unless-stopped

  estatico:
    build:
      context: .
      dockerfile: loader-estatico/Dockerfile
    container_name: metamapa-estatico
    ports:
      - "8101:8101"
    environment:
      <<: *db_env
      DB_NAME: loader_estatico
    volumes:
      - ./datos:/data:ro
    networks: [ metamapa-net ]
    restart: unless-stopped

  metamapa:
    build:
      context: .
      dockerfile: loader-metamapa/Dockerfile
    container_name: metamapa-metamapa
    ports:
      - "8103:8103"
    environment:
      <<: *db_env
      DB_NAME: loader_metamapa
    networks: [ metamapa-net ]
    restart: unless-stopped

  getaway:
    build:
      context: .
      dockerfile: getaway/Dockerfile
    container_name: metamapa-getaway
    ports:
      - "8080:8080"
      - "9091:9091"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - gestor
      - agregador
      - estadisticas
      - demo
      - dinamico
      - estatico
      - metamapa
    networks: [metamapa-net]
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:latest
    container_name: metamapa-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks: [metamapa-net]
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: metamapa-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks: [metamapa-net]
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"

  cadvisor:
      image: gcr.io/cadvisor/cadvisor:latest
      container_name: cadvisor
      restart: unless-stopped
      expose:
        - 8080
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw

  loki:
    image: grafana/loki:2.9.0
    container_name: metamapa-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml
      - loki-data:/loki
    networks: [ metamapa-net ]
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.0
    container_name: metamapa-promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - ./logs:/var/log/aplicaciones:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks: [ metamapa-net ]
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: metamapa-jaeger
    ports:
      - "16686:16686"
      - "14250:14250"
    networks: [ metamapa-net ]
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: metamapa-otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    networks: [ metamapa-net ]
    restart: unless-stopped

  frontend:
    build:
      context: ../Front_Metamapa
      dockerfile: Dockerfile
      args:
        VITE_URL_INICIAL_GESTOR: "http://${PUBLIC_IP}:8080/gestordatos"
        VITE_URL_INICIAL_DINAMICA: "http://${PUBLIC_IP}:8080/fuenteDinamica"
        VITE_URL_INICIAL_ESTADISTICAS: "http://${PUBLIC_IP}:8080/estadisticas"
        VITE_URL_INICIAL_DEMO: "http://${PUBLIC_IP}:8080/fuenteDemo"
        VITE_URL_INICIAL_ESTATICA: "http://${PUBLIC_IP}:8080/fuenteEstatica"
        VITE_URL_INICIAL_METAMAPA: "http://${PUBLIC_IP}:8080/fuenteMetamapa"
        VITE_URL_INICIAL_GETAWAY: "http://${PUBLIC_IP}:8080/getaway"
        VITE_URL_GOOGLE_AUTH: "http://${PUBLIC_IP}:8080/gestordatos"
        VITE_URL_GRAPHQL: "http://${PUBLIC_IP}:8080"

    container_name: metamapa-frontend
    ports:
      - "80:80"
    networks: [ metamapa-net ]
    restart: unless-stopped


networks:
  metamapa-net:

volumes:
  db-central-data:
  prometheus-data:
  grafana-data:
  loki-data:
