global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "agregador"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["agregador:8200"]

  - job_name: 'gestor'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gestor:8500']

  - job_name: 'estadisticas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['estadisticas:8600']

  - job_name: 'demo'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['demo:8700']

  - job_name: "dinamico"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["dinamico:8102"]

  - job_name: "estatico"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["estatico:8101"]

  - job_name: "metamapa"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["metamapa:8103"]

  - job_name: "getaway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["getaway:8080"]
