spring:
  application:
    name: loader-dinamico
server:
  port: 8102
loader:
  self:
    nombreFuente: "Fuente-dinamicaasasasasa"
    tipo: "DINAMICA"
    baseUrl: "http://localhost:8102/fuenteDinamica"

agregador:
  baseUrl: "http://localhost:8200"
logging:
  file:
    name: logs/dinamico/${loader.self.nombreFuente}.log
  level:
    root: INFO
    dinamico: DEBUG


