server:
  port: 8080

spring:
  application:
    name: getaway
  servlet:
    multipart:
      enabled: false

logging:
  level:
    root: INFO

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always


gateway:
  servicios:
    gestordatos: "http://gestor:8500"
    agregador: "http://agregador:8200"
    estadisticas: "http://estadisticas:8600"
    fuenteDinamica: "http://dinamico:8102"
    fuenteEstatica: "http://estatico:8101"
    fuenteDemo: "http://demo:8700"
    fuenteMetamapa: "http://metamapa:8103"
