server:
  port: 8080

spring:
  application:
    name: getaway
  servlet:
    multipart:
      enabled: false

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
