server:
  port: 8080

logging:
  level:
    root: INFO

spring:
  application:
    name: Getaway
  servlet:
    multipart:
      enabled: false

gateway:
  servicios:
    gestordatos: "http://localhost:8500"
    agregador: "http://localhost:8200"
    estadisticas: "http://localhost:8600"
    fuenteDinamica: "http://localhost:8102"
    fuenteEstatica: "http://localhost:8101"
    fuenteDemo: "http://localhost:8700"
    fuenteMetamapa: "http://localhost:8103"
