server:
  port: 8080

spring:
  application:
    name: getaway
  servlet:
    multipart:
      enabled: false

logging:
  level:
    root: INFO

management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always


gateway:
  servicios:
    gestordatos: "http://gestor:8500/gestordatos"
    agregador: "http://agregador:8200/agregador"
    estadisticas: "http://estadisticas:8600/estadisticas"
    fuenteDinamica: "http://dinamico:8102/fuenteDinamica"
    fuenteEstatica: "http://estatico:8101/fuenteEstatica"
    fuenteDemo: "http://demo:8700/fuenteDemo"
    fuenteMetamapa: "http://metamapa:8103/fuenteMetamapa"

