spring.application.name=gestor-datos

# ==== BASE DE DATOS MYSQL LOCAL ====
spring.datasource.url=jdbc:mysql://localhost:3306/central?useSSL=false&serverTimezone=America/Argentina/Buenos_Aires
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==== HIBERNATE / JPA ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=terribleContraseniaQueMeAcaboDeInventarChavales
jwt.expiration=86400000 

# Google OAuth2
google.client.id=310074938010-li1227rain2v0ub3f8cmdhbrh953j2qe.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8500/gestordatos/contribuyentes/google/callback

# Tu frontend
frontend.url=http://localhost:5173


# Asegurar que AOP funcione
spring.aop.auto=true
spring.aop.proxy-target-class=true

# ===== ACTUATOR / METRICS CONFIGURATION =====
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.enable.all=true
management.prometheus.metrics.export.enabled=true

# ===== METRICS DISTRIBUTION =====
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# ===== METRICS TAGS =====
management.metrics.tags.servicio=gestor-datos
management.metrics.tags.environment=${ENVIRONMENT:development}
management.metrics.tags.application=metamapa
