spring:
  application:
    name: gestor-datos

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8500
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

google:
  client:
    id: 310074938010-li1227rain2v0ub3f8cmdhbrh953j2qe.apps.googleusercontent.com
    secret: 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
  redirect:
    uri: https://metamapadds.org/gestordatos/contribuyentes/google/callback
