spring:
  application:
    name: gestor-datos
server:
  port: 8500
logging:
  file:
    name: logs/gestor-datos/gestor-datos.log
  level:
    root: INFO
    org.example.metamapa: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
app:
  cors:
    allowed-origins:
      - "http://localhost:8090"
      - "http://127.0.0.1:5500"
      - "http://localhost:3000"
      - "http://localhost:5173"
