server:
  port: 8101

spring:
  application:
    name: loader-estatico

loader:
  self:
    id: "loader-estatico-hogar"
    nombreFuente: "Fuente-CSV-HogarComunitario"
    tipo: "ESTATICA"
    baseUrl: "http://localhost:8101/fuenteEstatica"

fileserver:
  tipo: local  # o "remoto" o "drive"
  drive:
      folderId: 1MiPkqnRna43N7NZr3fL37IByscLwI_0B
      credentialsPath: # D:\UTN\TERCERO\Diseño de Sistemas\Grupo12DDS\loader-estatico\src\main\resources\credi
  basePath: "D:/UTN/TERCERO/Diseño de Sistemas/Grupo12DDS/datos" # si es local
  baseUrl: "http://localhost:8500/"     # si es remoto


agregador:
  baseUrl: "http://localhost:8200"

logging:
  file:
    name: logs/loader-estatico.log
  level:
    root: INFO
    org.example.metamapa: DEBUG
