server:
  port: 8101

spring:
  application:
    name: loader-estatico

loader:
  self:
    id: "loader-estatico-hogar"
    nombreFuente: "Fuente-CSV-HogarComunitario"
    tipo: "ESTATICA"
    baseUrl: "http://localhost:8101"

fileserver:
  tipo: local  # o "remoto"
  basePath: "/home/user/archivos-csv"  # si es local
  baseUrl: "http://localhost:8500"     # si es remoto


agregador:
  baseUrl: "http://localhost:8200"

