server:
  port: 8101

spring:
  application:
    name: loader-estatico

loader:
  self:
    nombreFuente: "Fuente-CSV-HogarComunitario"
    tipo: "ESTATICA"
    baseUrl: "http://localhost:8101"

fileserver:
  baseUrl: "http://localhost:8500"

agregador:
  baseUrl: "http://localhost:8200"

usarCron: true
