spring:
  application:
    name: agregador
server:
  port: 8200
agregador:
  cron: "0/30 * * * * *"
  timeout:
    segundos: 30

logging:
  file:
    name: logs/agregador/agregador.log
  level:
    root: INFO
    org.example.metamapa: DEBUG
