spring:
  application:
    name: loader-metamapa

  datasource:
    url: jdbc:mysql://db-central:3306/loader_metamapa?useSSL=false&serverTimezone=America/Argentina/Buenos_Aires&allowPublicKeyRetrieval=true
    username: metamapa
    password: metamapa_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8103

loader:
  id: "metamapa-joaco"
  self:
    nombreFuente: "Fuente-MetaMapa"
    tipo: "PROXY"
    # dentro de docker NO es localhost
    baseUrl: "http://metamapa:8103/fuenteMetamapa"
  registro:
    retryDelayMs: 10000

# dentro de docker NO es localhost
agregador:
  baseUrl: "http://agregador:8200"

logging:
  level:
    root: INFO
    org.example.metamapa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
