spring:
  application:
    name: loader-proxy
server:
  port: 8103
fuente:
  metamapa:
    url: https://telepathically-censorian-marlen.ngrok-free.dev/gestordatos
loader:
  id: metamapa-joaco
  self:
    nombreFuente: "Fuente-MetaMapa"
    tipo: "PROXY"
    baseUrl: "http://localhost:8103/fuenteMetamapa"

agregador:
  baseUrl: "http://localhost:8200"
logging:
  file:
    name: logs/metamapa/${loader.id}.log
  level:
    root: INFO
    org.example.metamapa: DEBUG
