spring:
  application:
    name: loader-demo
server:
  port: 8700

loader:
  id: loader-demo-oficial
  self:
    nombreFuente: "Fuente-Demo"
    tipo: "PROXY"
    baseUrl: "http://localhost:8700/fuenteDemo"
  registro:
    retryDelayMs: 10000

agregador:
  baseUrl: "http://localhost:8200"
logging:
  file:
    name: logs/demo/${loader.id}.log
  level:
    root: INFO
    org.example.metamapa: DEBUG


