spring:
  application:
    name: loader-demo
server:
  port: 8700
loaderdemo:
  fuente:
    url: https://conexion.fake-source.edu/api
loader:
  id: loader-demo-oficial
  self:
    nombreFuente: "Fuente-Demo"
    tipo: "PROXY"
    baseUrl: "http://localhost:8700"

agregador:
  baseUrl: "http://localhost:8200"


